/**
 * Builds a single-file version of an edge function for the Supabase
 * dashboard's web editor, which deploys only `index.ts` and does not bundle
 * sibling or shared files (the CLI does: `supabase functions deploy <name>`).
 *
 *   deno run --allow-read --allow-write supabase/tools/single_file.ts rubricatorApi
 *   deno run --allow-read --allow-write supabase/tools/single_file.ts google-books
 *   deno run --allow-read --allow-write supabase/tools/single_file.ts scrape-tr-books
 *   deno run --allow-read --allow-write supabase/tools/single_file.ts warm-genre-cache
 *
 * Writes supabase/functions/<name>/index.single.ts (git-ignored): paste its
 * contents into the dashboard editor as the function's index.ts. It is
 * generated -- edit the real sources, then rebuild.
 *
 * Relative imports (`./handler.ts`, `../_shared/*.ts`) are inlined, dependencies
 * first, and their `export`s dropped (one shared scope, nothing to export);
 * remote imports (jsr:, npm:, https:) are kept once at the top. Top-level names
 * must therefore be unique across the inlined modules -- `deno check` on the
 * output reports any clash.
 */
const name = Deno.args[0];
if (!name) {
  console.error("usage: single_file.ts <function-name>");
  Deno.exit(1);
}

const functionsDir = new URL("../functions/", import.meta.url);
const entry = new URL(`${name}/index.ts`, functionsDir);

// import ... from "x";  |  import "x";   (possibly multi-line)
const IMPORT_RE =
  /^import\s+(?:[\s\S]*?\s+from\s+)?["']([^"']+)["'];?[ \t]*\r?\n/gm;

// `export { a, b };` lists would clash with the inlined declarations.
const EXPORT_LIST_RE = /^export\s+\{[^}]*\};?[ \t]*\r?\n/gm;
// `export function|const|type|...` -> plain declaration.
const EXPORT_DECL_RE =
  /^export\s+(?=(?:async\s+)?(?:function|const|let|class|type|interface|enum)\b)/gm;

const remoteImports = new Set<string>();
const bodies: string[] = [];
const visited = new Set<string>();

async function visit(url: URL): Promise<void> {
  if (visited.has(url.href)) return;
  visited.add(url.href);
  const source = (await Deno.readTextFile(url))
    .replace(EXPORT_LIST_RE, "")
    .replace(EXPORT_DECL_RE, "");

  const deps: URL[] = [];
  const body = source.replace(IMPORT_RE, (statement, specifier: string) => {
    if (specifier.startsWith(".")) {
      deps.push(new URL(specifier, url));
    } else {
      remoteImports.add(statement.trimEnd());
    }
    return "";
  });

  for (const dep of deps) await visit(dep); // dependencies first
  const label = url.pathname.split("/functions/")[1] ?? url.pathname;
  bodies.push(`// ---- ${label} ----\n${body.trim()}\n`);
}

await visit(entry);

const out =
  `// GENERATED by supabase/tools/single_file.ts ${name} -- do not edit.
// Single-file build of the "${name}" edge function (entry + its local and
// shared modules) for pasting into the Supabase dashboard editor.
${[...remoteImports].join("\n")}

${bodies.join("\n")}`;

const target = new URL(`${name}/index.single.ts`, functionsDir);
await Deno.writeTextFile(target, out);
console.log(
  `wrote ${target.pathname} (${out.length} bytes, ${visited.size} modules)`,
);
